name: 'Firflant Starter'
description: 'Minimal install plus basic Page content type and Content editor role (as in standard profile), Canvas, and Tailwind theme. No frontpage view.'
type: 'Site'

recipes: []

install:
  - filter
  - text
  - path
  - contextual
  - file
  - toolbar
  - canvas
  - config_ignore
  - filefield_paths
  - focal_point
  - imageapi_optimize
  - page_analytics
  - token
  - tailwind

config:
  import:
    filter:
      - filter.format.basic_html
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: tailwind
        admin: claro
